{{- if .Values.persistence.elasticsearch.enabled -}}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: reportportal-elasticsearch
  namespace: reportportal
  labels: {{ include "labels" . | indent 4 }}
  type: amazonEBS
  purpose: reportportal-elasticsearch
spec:
 capacity:
   storage: 80Gi
 accessModes:
   - ReadWriteOnce
 awsElasticBlockStore:
   volumeID: vol-000000000
   fsType: ext4
 storageClassName: gp2
{{- end -}}
