{{- if .Values.persistence.elasticsearch.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: reportportal-elasticsearch 
  namespace: reportportal
  labels: {{ include "labels" . | indent 4 }}
  purpose: reportportal-elasticsearch 
  type: amazonEBS
spec:
 accessModes:
   - ReadWriteOnce
 resources:
   requests:
      storage: 80Gi
 selector:
 matchLabels:
 purpose: reportportal-elasticsearch 
{{- end -}}
