{{- if .Values.persistence.mongodb.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
   name: reportportal-mongodb
   namespace: reportportal
   labels: {{ include "labels" . | indent 4 }}
   purpose: reportportal-mongodb
   type: amazonEBS
spec:
 accessModes:
   - ReadWriteOnce
 resources:
   requests:
     storage: 75Gi
 selector:
 matchLabels:
 purpose: reportportal-mongodb
{{- end -}}
