apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: reportportal
  labels: {{ include "labels" . | indent 4 }}
spec:
  ports:
  - port: 27017
    targetPort: 27017
  selector:
    component: reportportal-mongodb
  type: ClusterIP
