{{- if .Values.persistence.registry.enabled -}}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: reportportal-registry
  namespace: reportportal
  labels: {{ include "labels" . | indent 4 }}
  type: amazonEBS
  purpose: reportportal-registry
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  awsElasticBlockStore:
    volumeID: vol-00000000000000 
    fsType: ext4
  storageClassName: gp2
{{- end -}}
