{{- if .Values.persistence.registry.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
   name: reportportal-registry
   namespace: reportportal
   labels: {{ include "labels" . | indent 4 }}
   purpose: reportportal-registry 
   type: amazonEBS
spec:
   accessModes:
     - ReadWriteOnce
   resources:
     requests:
       storage: 50Gi
   selector:
   matchLabels:
   purpose: reportportal-registry 
{{- end -}}
